#!/bin/sh

errcode=0
errcode="success"

sh /usr/bin/swupdate_chk.sh 2>/dev/null 1>/dev/null
errcode=$?

if [ "$errcode" -ne 0 ];then
  errstring="Get system/USB Modem/Security firmware information fail."
else
  errstring="Get system/USB Modem/Security firmware information success."
fi

if [ "$errcode" -ne 0 ];then
	echo "error-message \"$errstring\""
	exit 1
else
	exit 0
fi

