#!/bin/sh
errstr="Success"
external_port=$2
internal_port=$4
ipaddress=$6
protocol=`iptables -w -t nat -L MINIUPNPD |grep dpt:$external_port |grep $ipaddress:$internal_port |awk -F ' ' '{print $2}'`
iptables -w -t nat -D MINIUPNPD -p $protocol --dport $external_port -j DNAT --to-destination $ipaddress:$internal_port
status=$?
if [ "$status" -ne 0 ];then
   errstr="Upnp Deletion Failed"
fi

if [ "$status" -ne 0 ];then
	echo "error-message \"$errstr\" "
	exit 1
else
	exit 0
fi
