#!/bin/sh

testemailserver="/usr/bin/testserver"
`$testemailserver`

errcode=$?

if [ "$errcode" -ne 0 ];then
	errstring="Failed"
else
	errstring="Success"
fi

if [ "$errcode" -ne 0 ];then
	echo "error-message $errstring"
	exit 1
else
	exit 0
fi
