#!/bin/sh

errcode=1
errstring="Invalid Arguments"
SWITCH_QOS_STATS_FILE="/tmp/stats/switch_qos_reset_stats"

	# send signal to operdb_stats to clear the saved counters
	`/usr/bin/sendOpsdbSignal.sh SIGCONT`

	/usr/sbin/bcmssdk -Q 1 -r 1
        errcode=$?
        if [ "$errcode" -ne 0 ];then
                errstring="Counters for Switch QOS are not reset"
		errcode=1
        else
		reset_uptime=`cat /proc/uptime | cut -d " " -f 1 | cut -d . -f 1`
		echo "$reset_uptime" > $SWITCH_QOS_STATS_FILE
		errcode=0
        fi

if [ "$errcode" -ne 0 ];then
	echo "error-message \"$errstring\""
	exit 1
else
	exit 0
fi
