#!/bin/sh
# input: "ACTION connection-name <connection-name>"
# output: "code <int32> errstr <string>"

ACTION=$1

uci show strongswan.s2s_$3 >/dev/null 2>&1
if [ $? -eq 0 ]
then
	CONNNAME="s2s_$3"
	[ "$ACTION" == "down" ] && {
		/etc/init.d/strongswan exec_ipsec "$ACTION" "$CONNNAME"_bkp >/dev/null 2>&1
	}
else
	CONNNAME="goi_$3"
fi

logger -t VPN-RPC "Executing RPC for connection $3 to bring $1"
/etc/init.d/strongswan exec_ipsec "$ACTION" "$CONNNAME" >/dev/null 2>&1
if [ "$?" -ne 0 ]
then
	errcode=1
	errstring="Failed"
else
	errcode=0
	errstring="Success"
fi

if [ "$errcode" -ne 0 ];then
	echo "error-message $errstring"
	exit 1
else
	exit 0
fi
