#!/bin/sh

UTILITY_NAME="/tmp/utility-traceroute"
TRACEROUTE_UTILITY=

init_ttl=`echo $@ | awk '{for (I=1;I<=NF;I++) if ($I == "initial-ttl") {print $(I+1)};}'`
max_ttl=`echo $@ | awk '{for (I=1;I<=NF;I++) if ($I == "max-ttl") {print $(I+1)};}'`
target=`echo $@ | awk '{for (I=1;I<=NF;I++) if ($I == "target") {print $(I+1)};}'`

value=`echo $target | egrep "(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))"`
if [ -n "$value" ];then
	TRACEROUTE_UTILITY=traceroute6
else
	TRACEROUTE_UTILITY=traceroute
fi

TRACEROUTE_COMMAND=$TRACEROUTE_UTILITY

if [ -n "$init_ttl" ];then
	TRACEROUTE_COMMAND=$TRACEROUTE_COMMAND" -f "$init_ttl
fi


if [ -n "$max_ttl" ];then
	TRACEROUTE_COMMAND=$TRACEROUTE_COMMAND" -m "$max_ttl
fi

# We are adding -q and -n option to match the rpc output format
TRACEROUTE_COMMAND=$TRACEROUTE_COMMAND" -n "

TRACEROUTE_COMMAND=$TRACEROUTE_COMMAND" "$target

# Prepare Output
$TRACEROUTE_COMMAND &> $UTILITY_NAME

errcode=$?

job_id=$(ps | grep traceroute | grep $target | sed s/"^ *"//g | cut -f 1 -d ' ')

if [ -z "$job_id" ]; then
        job_id=`awk -vmin=1000 -vmax=2000 'BEGIN{srand(); print int(min+rand()*(max-min+1))}'`
fi

 outfile="$UTILITY_NAME"_"$job_id"

 cp -f $UTILITY_NAME $outfile
 echo "job-id \"$job_id\""

if [ "$errcode" -ne 0 ];then
        exit $errcode
else
	exit 0
fi
