#!/bin/sh


UTILITY_NAME="/tmp/utility-ping"
PING_UTILITY=
counter=0

count=`echo $@ | awk '{for (I=1;I<=NF;I++) if ($I == "echo-count") {print $(I+1)};}'`
size=`echo $@ | awk '{for (I=1;I<=NF;I++) if ($I == "size") {print $(I+1)};}'`
ttl=`echo $@ | awk '{for (I=1;I<=NF;I++) if ($I == "ttl") {print $(I+1)};}'`
timeout=`echo $@ | awk '{for (I=1;I<=NF;I++) if ($I == "timeout") {print $(I+1)};}'`
version=`echo $@ | awk '{for (I=1;I<=NF;I++) if ($I == "ip-version") {print $(I+1)};}'`
target=`echo $@ | awk '{for (I=1;I<=NF;I++) if ($I == "target") {print $(I+1)};}'`

if [ -n "$version" ];then
	if [ "$version" = "ipv4" ];then
		PING_UTILITY=ping	
	else
		PING_UTILITY=ping6
	fi
else
	value=`echo $target | egrep "(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))"`
	if [ -n "$value" ];then
		PING_UTILITY=ping6
	else
		PING_UTILITY=ping
	fi
fi

PING_COMMAND=$PING_UTILITY
if [ -z "$count" ];then
	count=4
fi
PING_COMMAND=$PING_COMMAND" -c "$count

if [ -n "$size" ];then
	PING_COMMAND=$PING_COMMAND" -s "$size
fi


if [ -n "$ttl" ];then
	if [ "$PING_UTILITY" = "ping" ];then
		PING_COMMAND=$PING_COMMAND" -t "$ttl
	fi
fi


if [ -n "$timeout" ];then
	if [ "$PING_UTILITY" = "ping" ];then
		PING_COMMAND=$PING_COMMAND" -w "$timeout
	fi
fi

PING_COMMAND=$PING_COMMAND" "$target
# Prepare Output
$PING_COMMAND &> $UTILITY_NAME
errcode=$?

if [ "$errcode" -eq 0 ];then
	echo "address $target"

	sed -i "1d" $UTILITY_NAME
	sed -i "s/  */ /g" $UTILITY_NAME
	
	while read line
	do
		if [ "$counter" -lt "$count" ];then
			value=`echo $line | grep seq`
			if [ -n "$value" ];then
				ttl=`echo $line | cut -d " " -f 6 | cut -d = -f 2`
				time=`echo $line | cut -d " " -f 7 | cut -d = -f 2`
				echo "data __BEGIN icmp-seq $counter ttl $ttl time $time data __END"
			else
				echo "data __BEGIN icmp-seq $counter data __END"
			fi
			counter=`expr $counter + 1`
		else
			break
		fi
		
	done < $UTILITY_NAME	
else
	cat $UTILITY_NAME
fi

exit $errcode
