#!/usr/bin/perl
###########################################################################
# *  * Copyright 2015, Freescale Semiconductor, Inc. All rights reserved. #
###########################################################################

###########################################################################
#file: certscriptCtrl                                                     #
#This script is executed by certscript script to send certificate add or  #
#modify or del events to opsdb certificate module                         #
###########################################################################

use IO::Socket::INET;

$num_args = $#ARGV + 1;
if ($num_args != 1) {
    print "Usage: certscriptCtrl <cert_data>\n";
    exit;
}

# flush after every write
$| = 1;

my ($socket,$data);

#  We call IO::Socket::INET->new() to create the UDP Socket
# and bind with the PeerAddr.
$socket = new IO::Socket::INET (
        PeerAddr   => '127.0.0.1:5243',
        Proto        => 'udp'
) or die "ERROR in Socket Creation : $!\n";

#send operation
$socket->send($ARGV[0]);
$socket->close();

