#!/bin/sh
if [ -n "$1" ];then
	tmpOutFile="/tmp/dhcp_neigh_result"
	outFile="/tmp/neighbordata"
else
	tmpOutFile="/tmp/result"
        outFile="/tmp/stats/dhcp_bind_stats"
fi
rm -f $outFile
touch $outFile
`cut -f1,2,3,4 -d' ' /tmp/dhcp.leases > $tmpOutFile`

convertsecs() {
    h=`expr $1 / 3600`
    m=`expr $1  % 3600 / 60`
    s=`expr $1 % 60`
    printf "%02d hours %02d minutes %02d seconds\n" $h $m $s
}


while read first second third forth
do
oIFS="$IFS";IFS="-"
set $forth
IFS="$oIFS"

if_ipv4=$(echo $third | grep ".*\..*\..*\..*")

[ -n "$first" -a -n "$if_ipv4" ] && {

if [ $1 = "static" ]
then
forth="0"
else
forth="1"
fi

cursecs=`date +%s`
remsecs=`expr $first - $cursecs`
echo $third?$second?$remsecs?$forth >> $outFile

}

done < $tmpOutFile

rm -f $tmpOutFile

