#!/bin/sh
BASEPATH=/tmp
statsfile=$BASEPATH/stats/l2tp_stats
rm -f $statsfile
touch $statsfile
user_logfile="$BASEPATH/ppp_user_accounting.log"

pids=`pgrep -f "options.xl2tpd" 2>/dev/null`

[ -n "$pids" ] && {
for pid in $pids
do
	session_id=$pid
	client_vir_ip=`cat /proc/$pid/cmdline |xargs -0|cut -d ' ' -f 4|cut -d ':' -f 2`
	client_pub_ip=`cat /proc/$pid/cmdline |xargs -0|cut -d ' ' -f 14`
	connect_time=`grep $pid $user_logfile |cut -d ' ' -f 3|cut -d ':' -f 2`
	client_user_name=`grep $pid $user_logfile |cut -d ' ' -f 1|cut -d ':' -f 2`

	local lines=`echo "$session_id;$client_user_name;$client_pub_ip;$client_vir_ip;$connect_time" |wc -l`
	[ "$lines" == "1" ] && [ -n "$session_id" ] && [ -n "$client_vir_ip" ] && [ -n "$client_pub_ip" ] && [ -n "$connect_time" ] && [ -n "$client_user_name" ] && {
		echo "$session_id;$client_user_name;$client_pub_ip;$client_vir_ip;$connect_time"
	}
done > $statsfile
exit 0
}
#echo "0;NONE;0.0.0.0;0.0.0.0;0;0;0;0;0;0" > $statsfile
