#!/usr/bin/perl
###########################################################################
# *  * Copyright 2015, Freescale Semiconductor, Inc. All rights reserved. #
###########################################################################

###########################################################################
#file: timerCtrl.sh							  #
#This script is executed by strongswan init script to ADD/DEL connections #
#  from timer module.                                                     #
###########################################################################

use IO::Socket::INET;

$num_args = $#ARGV + 1;
if ($num_args != 1) {
    print "Usage: timerCtrl <+/-><connection-name>\n";
    print "	<+><connection-name> : is to Add the connection to timer module.\n";
    print "	<-><connection-name> : is to Delete the connection from timer module.\n";
    exit;
}

#print "$ARGV[0]";
# flush after every write
$| = 1;

my ($socket,$data);

#  We call IO::Socket::INET->new() to create the UDP Socket 
# and bind with the PeerAddr.
$socket = new IO::Socket::INET (
	PeerAddr   => '127.0.0.1:9999',
	Proto        => 'udp'
) or die "ERROR in Socket Creation : $!\n";

#send operation
$data = $ARGV[0];
$socket->send($data);

$socket->close();
