#!/bin/sh

logTimeThreashold=`uci get syslog.email.time_threshold`
log_enable=`uci get syslog.email.enable`
log_count=$(cat /var/log/SendEmailLogs | wc -l)
logThreashold=`uci get syslog.email.log_number_threshold`


if [ "$logTimeThreashold" = "2" ] && [ "$log_enable" = "1" ] && [ "$log_count" -ge "1" ]; then
	process_count=`ps | grep /usr/bin/sendmaillog | grep -v "grep /usr/bin/sendmaillog" | wc -l`
	process_count=$((process_count+1))
	head -n $logThreashold /var/log/SendEmailLogs > /var/log/SendEmailLogs${process_count}
	cp -f /var/log/SendEmailLogs /var/log/tmpLogs
	sed -i "1,${logThreashold}d" /var/log/tmpLogs
	echo "" > /var/log/SendEmailLogs
	cat /var/log/tmpLogs > /var/log/SendEmailLogs
	/usr/bin/sendmaillog "/var/log/SendEmailLogs${process_count}" &
fi
