#!/bin/sh

PID=`uci get systeminfo.sysinfo.pid`
SERIAL=`uci get systeminfo.sysinfo.serial_number`
FROM=`uci get email.email_settings.from_email_address1`
To1=`uci get email.email_settings.to_email_address1`
To2=""
hostname=`uci get systemconfig.system.hostname`
uci_email2=`uci show email | grep to_email_address2`
if [ -n "$uci_email2" ];then
	        To2=`uci get email.email_settings.to_email_address2`
fi

# Prepare the Mail File
`echo "This is the test mail" > /tmp/sendTestMail`
`sed -i "1i Subject: \"$hostname($SERIAL)\" Test Mail" /tmp/sendTestMail`
if [ -n "$To2" ];then
	`sed -i "1i To: $To2" /tmp/sendTestMail`
fi
`sed -i "1i To: $To1" /tmp/sendTestMail`
`sed -i "1i From: \"$PID($SERIAL)\" <$FROM>" /tmp/sendTestMail`

if [ -n "$To2" ];then
	cat /tmp/sendTestMail | msmtp $To1 $To2 --syslog >/dev/null 2>&1
else
	cat /tmp/sendTestMail | msmtp $To1 --syslog >/dev/null 2>&1
fi
