#!/bin/sh
# This script is executed as part of the hotplug event with
# HOTPLUG_TYPE=iface, triggered by various scripts when an interface
# is configured (ACTION=ifup) or deconfigured (ACTION=ifdown).  The
# interface is available as INTERFACE, the real device as DEVICE.

[ "$ACTION" == "rtupd" ] && exit 0
[ "$DEVICE" == "lo" ] && exit 0
                 
case "$ACTION" in
	ifdown)
	ppp_iface=$(echo $INTERFACE | grep wan[0-9].*p.* )
	if [ "$ppp_iface" != "" ]; then
		demand-interface-up $INTERFACE &
	fi
	;;
	ifup)
	if [ "$(echo $DEVICE | grep ppoe-wan.6p.*)" ]; then
		echo 2 >/proc/sys/net/ipv6/conf/$DEVICE/accept_ra
	fi
	;;
esac
