#!/bin/sh /etc/rc.common

. /lib/functions.sh
. /lib/functions/network.sh

#START=
boot() {
	board=`uci get systeminfo.sysinfo.pid | cut -d'-' -f1`
	if [ "$board" = "RV340" -o "$board" = "RV340W" ]; then
		logger -t system "Boot pattern, progress percentage: 100%. Setting switch LED to NORMAL operation."
		rtkssdk bootled -i 4
	fi	
}
