#!/bin/sh /etc/rc.common

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

. /lib/functions/network.sh
. /lib/netifd/netifd-proto.sh
. /lib/config/uci.sh

start() {
	netifd_process=$(ps -eaf | grep netifd | grep -v "grep" | awk -F ' ' '{print $1}')
	service_start /sbin/netifd
	for i in $netifd_process
	do
		logger -t netifd "killing process with pid $i"
		kill -9 $i
	done
}
