#!/bin/sh /etc/rc.common

START=54

CONF=/etc/config/fastforward
OPTIONS="-f $CONF"

start() {
        if [ -e /proc/fppmode ]; then
	  if [ "`grep "0" /proc/fppmode`" ]; then
            exit 0
          fi
        fi
	insmod nfnetlink 2> /dev/null
if [ "`uname -r`" \> "2.6.32" ]; then
	if ! lsmod | grep "nf_defrag_ipv4" &> /dev/null; then
		insmod nf_defrag_ipv4 2> /dev/null
	fi
fi
	
	if ! lsmod | grep "nf_conntrack" &> /dev/null; then
		insmod nf_conntrack 2> /dev/null
	fi
	if ! lsmod | grep "nf_conntrack_ipv4" &> /dev/null; then
		insmod nf_conntrack_ipv4 2> /dev/null
	fi
	if ! lsmod | grep "nf_conntrack_ipv6" &> /dev/null; then
		insmod nf_conntrack_ipv6 2> /dev/null
	fi
	if ! lsmod | grep "nf_nat" &> /dev/null; then
		insmod nf_nat  2> /dev/null
	fi
	if ! lsmod | grep "nf_conntrack_netlink" &> /dev/null; then
		insmod nf_conntrack_netlink  2> /dev/null
	fi

	[ -d /var/run ] || mkdir -p /var/run
	board_name=$(cat /proc/cpuinfo | grep "Comcerto" | cut -d'(' -f 2 | cut -d' ' -f 1)
#	echo "board_name=$board_name"
	if [ "$board_name" = "Router" ]; then
	  nf_conntrack_max=$(cat /etc/sysctl.conf | grep "nf_conntrack_max" | cut -d'=' -f 2)
	  if [ -n "$nf_conntrack_max" -a "$nf_conntrack_max" -gt 0 ]; then
	    OPTIONS="$OPTIONS -n"
	    OPTIONS="$OPTIONS $nf_conntrack_max"
	  fi
	fi
#	echo "cmm OPTIONS is $OPTIONS"
        /usr/bin/cmm $OPTIONS

	#[ -e /etc/init.d/qos ] && sleep 1 && /etc/init.d/qos restart
	[ -e /etc/ppp/ip-up.d/l2tp.sh ] && sleep 2 && /etc/ppp/ip-up.d/l2tp.sh
}

stop() {
        if [ -e /proc/fppmode ]; then
	  if [ "`grep "0" /proc/fppmode`" ]; then
            exit 0
          fi
        fi
        [ -f /var/run/cmm.pid ] && kill $(cat /var/run/cmm.pid) >/dev/null 2>&1
	rmmod nf_conntrack_netlink 2> /dev/null
	rmmod nf_nat 2> /dev/null
	rmmod nf_conntrack_ipv6 2> /dev/null
	rmmod nf_conntrack_ipv4 2> /dev/null
	rmmod nfnetlink 2> /dev/null
}

