#!/bin/sh /etc/rc.common
# 16-03-2017: yulin.chen <yulin.chen@deltaww.com>
# Add UCI file check script

START=12

start() {
	local floder="/tmp/etc/config"
	local file_260x="dmz mwan3 license webfilter"
	local file_p="poeconf"
	local file_w="wireless"
	local pid=`uci get systeminfo.sysinfo.pid | awk -F '-' '{print $1}' | tr '[A-Z]' '[a-z]'`
	if [ "${pid/260/}" = "${pid}" ]; then
		for name in ${file_260x}
		do
			rm ${floder}/${name} > /dev/null 2>&1
		done
	fi
	if [ "${pid/p/}" = "${pid}" ]; then
		for name in ${file_p}
		do
			rm ${floder}/${name} > /dev/null 2>&1
		done
	fi
	if [ "${pid/w/}" = "${pid}" ]; then
		for name in ${file_w}
		do
			rm ${floder}/${name} > /dev/null 2>&1
		done
	fi
}
