#!/bin/sh

##Rest API: PUT /v1/organizations/{organizationId}/policies/{policyId}/identities/{originId}
##This API associate a policy identified by policyId to a device identified by originId.
##Command:
#curl -i -X PUT https://management.api.umbrella.com/v1/organizations/2251171/policies/661379/identities/124401076 --user 'e2ca354f65c24068afac72758669e061:a7eb4ef43e2a48229ce87add8b8e98e0' --header "Content-Type: application/json"
##Output:
#HTTP/1.1 200 OK /* no return parameters only the success code */
##--------- rest of the HTTP header--------------

. /usr/share/libubox/jshn.sh

#logger -t rpc-testing "Called $0 with args: $@"

RPC_OUTPUT=/tmp/odns_policy_output
RPC_DEBUG=/tmp/odns_debug_output
CURL="/usr/bin/curl"

#extract values from name value pair
key=`echo $@ | awk '{for (I=1;I<=NF;I++) if ($I == "key") {print $(I+1)};}'`
secret=`echo $@ | awk '{for (I=1;I<=NF;I++) if ($I == "secret") {print $(I+1)};}'`
ca=`echo $@ | awk '{for (I=1;I<=NF;I++) if ($I == "ca") {print $(I+1)};}'`

org_id=`echo $@ | awk '{for (I=1;I<=NF;I++) if ($I == "organization-id") {print $(I+1)};}'`
policy_id=`echo $@ | awk '{for (I=1;I<=NF;I++) if ($I == "policy-id") {print $(I+1)};}'`
origin_id=`echo $@ | awk '{for (I=1;I<=NF;I++) if ($I == "origin-id") {print $(I+1)};}'`

[ -z "$key" ] && {
	key=$(uci get umbrella.netdev_config_0.key)
}

[ -z "$secret" ] && {
	secret=$(uci get umbrella.netdev_config_0.secret)
}

#error codes
ODNS_SUCCESS=0
ODNS_FAILURE=1
errcode=$ODNS_SUCCESS
#ERR_RETURN="echo \"code $errcode errstr $errString\""

#clear the contents of the debug file
echo -n "" > $RPC_DEBUG
echo "$0: key=$key secret=$secret ca=$ca orgid=$org_id polid=$policy_id originid=$origin_id" > $RPC_DEBUG
echo "no. of argument:" $# > $RPC_DEBUG

#validating the input arguments
if [ -z $org_id ];then
    echo "not-ok __BEGIN error-code 1 error-message \"organization-id is missing\" not-ok __END"
    exit 0
elif [ -z $policy_id ] || [ -z $origin_id ];then
    echo "not-ok __BEGIN error-code 1 error-message \"policy-id or origin-id is missing\" not-ok __END"
    exit 0
elif [ -z $key ] || [ -z $secret ];then
    echo "not-ok __BEGIN error-code 1 error-message \"key or secret is missing\" not-ok __END"
    exit 0
fi


#Athentication Credentials
KEY="$key:$secret"
#Server Url
URL="https://management.api.umbrella.com/v1/organizations/$org_id"

update_replace_a_policy ()
{
	isFailure=$(cat $RPC_OUTPUT | grep error)
	isAuthFailure=$(cat $RPC_OUTPUT | grep message)

	if [ -n "$isFailure" ]
	then
		#Failure case 403/404

		local __tmp=$(cat $RPC_OUTPUT)

		json_init
		json_load "${__tmp:-{}}"

		#json_get_keys __keys
		#echo "keys: $__keys"

		json_get_var statusCode statusCode
		json_get_var error error
		json_get_var txId txId

		echo "not-ok __BEGIN error-code $statusCode error-message \"$error\" tx-id \"$txId\" not-ok __END"
	elif [ -n "$isAuthFailure" ]
	then
		local __tmp=$(cat $RPC_OUTPUT)

		json_init
		json_load "${__tmp:-{}}"

		json_get_var message message
		echo "not-ok __BEGIN error-code 403 error-message \"$message\" not-ok __END"
	else
		#Success case. We don't get any Json data for this case.
		echo "success-code 200"
	fi
}

#Associate the policy identified by $policy_id to the device identified by $origin_id
$CURL $URL/policies/$policy_id/identities/$origin_id -X PUT --user $KEY --header "Content-Type: application/json" -k 2>/dev/null > $RPC_OUTPUT
[ "$?" != "0" ] && {
	echo "not-ok __BEGIN error-code 1 error-message \"Network Error\" not-ok __END"
	exit 0
}

#call your function
update_replace_a_policy
exit 0
