#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=92
STOP=27

. /lib/config/uci.sh
. /lib/functions.sh
. /lib/functions/network.sh

TEMP_FILE=/tmp/ripinterfaces

start() {

	config_load rip

	if [ -n "$1" ]; then
		cat /tmp/rip | cut -f 2 -d '.'  | cut -f 1 -d '=' | sort -ur > $TEMP_FILE

		config_get_bool v4 global ipv4 0 #default is zero.
		config_get_bool v6 global ipv6 0

	        [[ "$v4" = "0" && "$v6" = "0" ]] && {
			vtysh -c "conf t" -c "no router rip" -c "no router ripng" -c "no log syslog" -c "no debug rip events" -c "no debug ripng events" -c "exit" -c "exit"
			exit 0
		}
	else
		vtysh -c "conf t" -c "log syslog debugging" -c "debug rip events" -c "debug ripng events" -c "exit" -c "exit"
		uci show rip | awk -F '.' '{print $2}' | awk -F '=' '{print $1}' | sort -ur > $TEMP_FILE
	fi

	config_get_bool v4 global ipv4 0 #default is zero.
	config_get_bool v6 global ipv6 0

while read -r line
do
#{
        new=$line

if [ "$new" = global ]; then
	if [ "$v4" = 1 ]; then
		vtysh -c "conf t" -c "log syslog debugging" -c "debug rip events" -c "router rip" -c "exit" -c "exit"
        else
		vtysh -c "conf t" -c "no router rip" -c "no debug rip events" -c "exit" -c "exit"
        fi

	if [ "$v6" = 1 ]; then
		vtysh -c "conf t" -c "log syslog debugging" -c "debug ripng events" -c "router ripng" -c "exit" -c "exit"
        else
		vtysh -c "conf t" -c "no router ripng" -c "no debug ripng events" -c "exit" -c "exit"
	fi

	[[ "$v4" = "0" && "$v6" = "0" ]] && {
		vtysh -c "conf t" -c "no log syslog" -c "exit" -c "exit"
	}

else
	if [ "$v4" = "1" ]; then
	#{
		if [ "$(echo $new | grep wan)" != "" ]; then
			network_get_mwaniface_cached iface_name $new
			network_get_physdev_cached v4_name $new
		else
			network_get_device_cached v4_name $new
			iface_name=$v4_name
		fi
		if [ "$v4_name" != "$iface_name" ];then
			vtysh -c "conf t" -c "router rip" -c "no network $v4_name" -c "no passive-interface $v4_name" -c "quit" -c "exit" -c "exit"
			vtysh -c "conf t" -c "interface $iface_name" -c "link-detect" -c "exit" -c "exit"
		else
			down_int=`vtysh -c "show interface description" -c "exit" | grep -E "wan" | grep "down" | awk -F ' ' '{print $1}'`
			for i in $down_int
			do
				vtysh -c "conf t" -c "router rip" -c "no network $i" -c "no passive-interface $i" -c "quit" -c "exit" -c "exit"
			done
		fi

	        vtysh -c "conf t" -c "interface $iface_name" -c "ip rip split-horizon poisoned-reverse" -c "ipv6 ripng split-horizon poisoned-reverse" -c "quit" -c "exit" -c "exit"

		config_get s1 "$new" v1_active ""
		config_get r1 "$new" v1_passive ""
		config_get s2 "$new" v2_active ""
		config_get r2 "$new" v2_passive ""

                #For gre interface creating access-list
                if [ "$(echo $new | grep gre)" != "" ]; then
                        devicename="gre-$new"
                        perl /usr/bin/distribute-rip.pl $devicename add
                fi

                if [ "$s1" = "" ]; then
                #interface is deleted
                        if [ "$(echo $new | grep gre)" != "" ]; then
                                devicename="gre-$new"
                                perl /usr/bin/distribute-rip.pl $devicename del
                                vtysh -c "conf t" -c "router rip" -c "no network $devicename" -c "version 2" -c "redistribute kernel" -c "redistribute static" -c "redistribute connected" -c "quit" -c "exit" -c "exit"
                                vtysh -c "conf t" -c "router rip" -c "no passive-interface $devicename" -c "no interface $devicename" -c "quit" -c "exit" -c "exit"
                        fi
                fi

		#enable/passive of ripv1 and ripv2
		#{
		case "$s1$r1$s2$r2" in
		1000)
			vtysh -c "conf t" -c "router rip" -c "network $iface_name" -c "version 1" -c "redistribute kernel" -c "redistribute static" -c "redistribute connected" -c "no passive-interface $iface_name" -c "quit" -c "exit" -c "exit"
	
			vtysh -c "conf t" -c "interface $iface_name" -c "no ip rip send version 1" -c "no ip rip receive version 1" -c "no ip rip send version 2" -c "no ip rip receive version 2" -c "ip rip send version 1" -c "ip rip receive version 1" -c "quit" -c "exit" -c "exit"
		;;
		1100)
			vtysh -c "conf t" -c "router rip" -c "network $iface_name" -c "version 1" -c "redistribute kernel" -c "redistribute static" -c "redistribute connected" -c "passive-interface $iface_name" -c "quit" -c "exit" -c "exit"

			vtysh -c "conf t" -c "interface $iface_name" -c "no ip rip send version 1" -c "no ip rip receive version 1" -c "no ip rip send version 2" -c "no ip rip receive version 2" -c "ip rip receive version 1" -c "quit" -c "exit" -c "exit"
		;;
		0010)

			vtysh -c "conf t" -c "router rip" -c "network $iface_name" -c "version 2" -c "redistribute kernel" -c "redistribute static" -c "redistribute connected" -c "no passive-interface $iface_name" -c "quit" -c "exit" -c "exit"
	
			vtysh -c "conf t" -c "interface $iface_name" -c "no ip rip send version 1" -c "no ip rip receive version 1" -c "no ip rip send version 2" -c "no ip rip receive version 2" -c "ip rip send version 2" -c "ip rip receive version 2" -c "quit" -c "exit" -c "exit"
		;;
		0011)

			vtysh -c "conf t" -c "router rip" -c "network $iface_name" -c "version 2" -c "redistribute kernel" -c "redistribute static" -c "redistribute connected" -c "passive-interface $iface_name" -c "quit" -c "exit" -c "exit"

			vtysh -c "conf t" -c "interface $iface_name" -c "no ip rip send version 1" -c "no ip rip receive version 1" -c "no ip rip send version 2" -c "no ip rip receive version 2" -c "ip rip receive version 2" -c "quit" -c "exit" -c "exit"
		;;
		1010)

			vtysh -c "conf t" -c "router rip" -c "network $iface_name" -c "version 2" -c "redistribute kernel" -c "redistribute static" -c "redistribute connected" -c "no passive-interface $iface_name" -c "quit" -c "exit" -c "exit"

			vtysh -c "conf t" -c "interface $iface_name" -c "no ip rip send version 1" -c "no ip rip receive version 1" -c "no ip rip send version 2" -c "no ip rip receive version 2" -c "ip rip send version 1 2" -c "ip rip receive version 1 2" -c "quit" -c "exit" -c "exit"
		;;
		1111)

			vtysh -c "conf t" -c "router rip" -c "network $iface_name" -c "version 2" -c "redistribute kernel" -c "redistribute static" -c "redistribute connected" -c "passive-interface $iface_name" -c "quit" -c "exit" -c "exit"

			vtysh -c "conf t" -c "interface $iface_name" -c "no ip rip send version 1" -c "no ip rip receive version 1" -c "no ip rip send version 2" -c "no ip rip receive version 2" -c "ip rip send version 1 2" -c "ip rip receive version 1 2" -c "quit" -c "exit" -c "exit"
		;;
		0000)
			vtysh -c "conf t" -c "router rip" -c "no network $iface_name" -c "version 2" -c "redistribute kernel" -c "redistribute static" -c "redistribute connected" -c "no passive-interface $iface_name" -c "quit" -c "exit" -c "exit"

			vtysh -c "conf t" -c "interface $iface_name" -c "no ip rip send version 1" -c "no ip rip receive version 1" -c "no ip rip send version 2" -c "no ip rip receive version 2" -c "quit" -c "exit" -c "exit"
		;;
		0101)

			vtysh -c "conf t" -c "router rip" -c "no network $iface_name" -c "version 2" -c "redistribute kernel" -c "redistribute static" -c "redistribute connected" -c "no passive-interface $iface_name" -c "quit" -c "exit" -c "exit"

			vtysh -c "conf t" -c "interface $iface_name" -c "no ip rip send version 1" -c "no ip rip receive version 1" -c "no ip rip send version 2" -c "no ip rip receive version 2" -c "quit" -c "exit" -c "exit"
		;;
		1101)
			vtysh -c "conf t" -c "router rip" -c "network $iface_name" -c "version 1" -c "redistribute kernel" -c "redistribute static" -c "redistribute connected" -c "passive-interface $iface_name" -c "quit" -c "exit" -c "exit"

			vtysh -c "conf t" -c "interface $iface_name" -c "no ip rip send version 1" -c "no ip rip receive version 1" -c "no ip rip send version 2" -c "no ip rip receive version 2" -c "ip rip receive version 1" -c "quit" -c "exit" -c "exit"
		;;
		0111)
			vtysh -c "conf t" -c "router rip" -c "network $iface_name" -c "version 2" -c "redistribute kernel" -c "redistribute static" -c "redistribute connected" -c "passive-interface $iface_name" -c "quit" -c "exit" -c "exit"

			vtysh -c "conf t" -c "interface $iface_name" -c "no ip rip send version 1" -c "no ip rip receive version 1" -c "no ip rip send version 2" -c "no ip rip receive version 2" -c "ip rip receive version 2" -c "quit" -c "exit" -c "exit"
		;;
		0001)
			vtysh -c "conf t" -c "interface $iface_name" -c "no ip rip send version 1" -c "no ip rip receive version 1" -c "no ip rip send version 2" -c "no ip rip receive version 2" -c "quit" -c "exit" -c "exit"

			vtysh -c "conf t" -c "router rip" -c "no network $iface_name" -c "version 2" -c "redistribute kernel" -c "redistribute static" -c "redistribute connected" -c "no passive-interface $iface_name" -c "quit" -c "exit" -c "exit"
		;;
		0100)
			vtysh -c "conf t" -c "interface $iface_name" -c "no ip rip send version 1" -c "no ip rip receive version 1" -c "no ip rip send version 2" -c "no ip rip receive version 2" -c "quit" -c "exit" -c "exit"

			vtysh -c "conf t" -c "router rip" -c "no network $iface_name" -c "version 2" -c "redistribute kernel" -c "redistribute static" -c "redistribute connected" -c "no passive-interface $iface_name" -c "quit" -c "exit" -c "exit"
		;;
		0110)
			vtysh -c "conf t" -c "router rip" -c "network $iface_name" -c "version 2" -c "redistribute kernel" -c "redistribute static" -c "redistribute connected" -c "no passive-interface $iface_name" -c "quit" -c "exit" -c "exit"

			vtysh -c "conf t" -c "interface $iface_name" -c "no ip rip send version 1" -c "no ip rip receive version 1" -c "no ip rip send version 2" -c "no ip rip receive version 2" -c "ip rip send version 2" -c "ip rip receive version 2" -c "quit" -c "exit" -c "exit"
		;;
		1001)
			vtysh -c "conf t" -c "router rip" -c "network $iface_name" -c "version 1" -c "redistribute kernel" -c "redistribute static" -c "redistribute connected" -c "no passive-interface $iface_name" -c "quit" -c "exit" -c "exit"

			vtysh -c "conf t" -c "interface $iface_name" -c "no ip rip send version 1" -c "no ip rip receive version 1" -c "no ip rip send version 2" -c "no ip rip receive version 2" -c "ip rip send version 1" -c "ip rip receive version 1" -c "quit" -c "exit" -c "exit"
		;;
		1011)
			vtysh -c "conf t" -c "router rip" -c "network $iface_name" -c "version 1" -c "redistribute kernel" -c "redistribute static" -c "redistribute connected" -c "no passive-interface $iface_name" -c "quit" -c "exit" -c "exit"

			vtysh -c "conf t" -c "interface $iface_name" -c "no ip rip send version 1" -c "no ip rip receive version 1" -c "no ip rip send version 2" -c "no ip rip receive version 2" -c "ip rip send version 1" -c "ip rip receive version 1 2"  -c "quit" -c "exit" -c "exit"
		;;
		1110)
			vtysh -c "conf t" -c "router rip" -c "network $iface_name" -c "version 2" -c "redistribute kernel" -c "redistribute static" -c "redistribute connected" -c "no passive-interface $iface_name" -c "quit" -c "exit" -c "exit"

			vtysh -c "conf t" -c "interface $iface_name" -c "no ip rip send version 1" -c "no ip rip receive version 1" -c "no ip rip send version 2" -c "no ip rip receive version 2" -c "ip rip send version 2" -c "ip rip receive version 1 2"  -c "quit" -c "exit" -c "exit"
		;;
		esac 
		#}

		config_get_bool auth "$new" auth 0
		[ "$auth" == "1" ] && {
			config_get mode "$new" auth_mode ""
			config_get str "$new" auth_string ""
		}
        
        	if [ "$auth" = 0 ]; then
	        	vtysh -c "conf t" -c "interface $iface_name" -c "no ip rip authentication mode" -c "no ip rip authentication key-chain" -c "no ip rip authentication string" -c "quit" -c "exit" -c "exit"
			vtysh -c "conf t" -c "no key chain $new" -c "quit" -c "exit" -c "exit" 2>&- >&-
		elif [ "$mode" = "md5" ]; then
	        	vtysh -c "conf t" -c "no key chain $new" -c "quit" -c "exit" -c "exit" 2>&- >&-
			vtysh -c "conf t" -c "interface $iface_name" -c "no ip rip authentication string" -c "quit" -c "exit" -c "exit"
			config_get key "$new" key ""
	        	vtysh -c "conf t" -c "interface $iface_name" -c "ip rip authentication mode md5" -c "quit" -c "exit" -c "exit"
	        	vtysh -c "conf t" -c "key chain $new" -c "key $key" -c "key-string $str" -c "quit" -c "exit" -c "exit"
	        	vtysh -c "conf t" -c "interface $iface_name" -c "ip rip authentication key-chain $new" -c "quit" -c "exit" -c "exit"
		else
			vtysh -c "conf t" -c "no key chain $new" -c "quit" -c "exit" -c "exit" 2>&- >&-
			vtysh -c "conf t" -c "interface $iface_name" -c "no ip rip authentication key-chain" -c "quit" -c "exit" -c "exit"
	        	vtysh -c "conf t" -c "interface $iface_name" -c "ip rip authentication mode text" -c "ip rip authentication string $str" -c "quit" -c "exit" -c "exit"
		fi
	#}
	fi	

	if [ "$v6" = 1 ]; then
	#{ #no support for v6 on GRE and USB 
		case "$new" in gre*) continue ;; usb*) continue ;; esac
		#enable ripng on interface
		config_get psv "$new" v6_passive
		config_get act "$new" v6_active

		case $new in 
		*vlan*)
			network_get_device_cached ifacev6_name $new
			iface_name=`uci get network.$new.ifname`
			;;
		wan*)
			v6_dev=$(echo $new | sed s/wan[0-9]*/\&6/g)
			network_get_waniface_cached ifacev6_name $v6_dev
			network_get_physdev_cached iface_name $v6_dev
			;;
		esac


		if [ "$ifacev6_name" != "$iface_name" ];then
			vtysh -c "conf t" -c "router ripng" -c "no network $iface_name" -c "no passive-interface $iface_name" -c "quit" -c "exit" -c "exit"
			if [ "$ifacev6_name" != "" ]; then
				iface_name=$ifacev6_name
				vtysh -c "conf t" -c "interface $iface_name" -c "link-detect" -c "exit" -c "exit"
			fi
		else
			down6_int=`vtysh -c "show interface description" -c "exit" | grep -E "wan" | grep "down" | awk -F ' ' '{print $1}'`
			for i in $down6_int
			do
				vtysh -c "conf t" -c "router ripng" -c "no network $i" -c "no passive-interface $i" -c "quit" -c "exit" -c "exit"
			done
		fi
		
	        if [ "$act" = 1 ]; then

			if [ "$psv" = 1 ]; then
				vtysh -c "conf t" -c "router ripng" -c "network $iface_name" -c "passive-interface $iface_name" -c "quit" -c "exit" -c "exit"
			else
				vtysh -c "conf t" -c "router ripng" -c "network $iface_name" -c "quit" -c "exit" -c "exit"
				vtysh -c "conf t" -c "router ripng" -c "network $iface_name" -c "redistribute kernel" -c "redistribute static" -c "redistribute connected" -c "quit" -c "exit" -c "exit"
				vtysh -c "conf t" -c "router ripng" -c "no passive-interface $iface_name" -c "quit" -c "exit" -c "exit"
			fi

		else
			vtysh -c "conf t" -c "router ripng" -c " no network $iface_name" -c "quit" -c "exit" -c "exit"
		fi
	#}
	fi
fi
#}
done < $TEMP_FILE

#For gre interface creating access-list
vtysh -c "conf t" -c "router rip" -c "no access-list myprefix" -c "exit" -c "exit"
network_active_wan_interfaces allWANiface
for iface in $allWANiface
do
	local isIPv6=`uci get network.$iface.ipv6 2>/dev/null`
	[ "$isIPv6" = "1" ] && continue
	network_get_subnet wannetmask "$iface"
	vtysh -c "conf t" -c "router rip" -c "access-list myprefix deny $wannetmask" -c "exit" -c "exit"
done
vtysh -c "conf t" -c "router rip" -c "access-list myprefix permit any" -c "exit" -c "exit"

}

reload() {
	cp /tmp/.uci/rip /tmp/rip
	global=$(cat /tmp/rip | awk -F '.' '{print $2}' | awk -F '=' '{print $1}' | sort -ur | grep global)
	uci commit rip
	if [ "$global" = "" ]; then
		start "/tmp/rip"
	else
		start
	fi
}
